runtime: nodejs20
service: network-monitor

env_variables:
  NODE_ENV: "production"
  UNIFI_API_KEY: "_t_gjSTdrUJNn825lQHitBY4CDQmXvN5"
  EMAIL_FROM: "dade.taher@gmail.com"
  EMAIL_APP_PASSWORD: "qcda dcco qhoz kepv"

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always
